services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"

  jobmanager:
    build:
      context: .
      dockerfile: ./infra/compute/flink/Dockerfile
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    volumes:
      - ./infra/compute/flink:/opt/flink/usrlib

  taskmanager:
    build:
      context: .
      dockerfile: ./infra/compute/flink/Dockerfile
    depends_on:
      - jobmanager
      - kafka
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        taskmanager.memory.process.size: 4096m
        taskmanager.memory.framework.off-heap.size: 256m
        taskmanager.memory.task.off-heap.size: 512m
    volumes:
      - .:/opt/flink/usrlib

  serving-api:
    build:
      context: .
      dockerfile: ./serving/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - kafka
    volumes:
      - .:/app

  data-simulator:
    build:
      context: .
      dockerfile: ./infra/compute/data_simulator/Dockerfile
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    command: python producer.py

  minio:
    build:
      context: .
      dockerfile: ./infra/storage/minio/Dockerfile
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio_data:/data



  minio-init:
    image: minio/mc
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD; do
        echo 'waiting for minio...';
        sleep 2;
      done;

      mc mb -p local/mlflow;

      echo 'bucket created';
      "
  mlflow:
    build:
      context: .
      dockerfile: ./infra/tracking/mlflow/Dockerfile

    ports:
      - "5000:5000"

    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-minioadmin}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-minioadmin}
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - MLFLOW_SERVER_ALLOWED_HOSTS=*
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root s3://mlflow
      --serve-artifacts
    depends_on:
      - minio

  training:
    build:
      context: .
      dockerfile: ./training/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - mlflow
      - minio
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI:-http://mlflow:5000}
      - MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT_URL:-http://minio:9000}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-minioadmin}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-minioadmin}
      - MLFLOW_EXPERIMENT_NAME=${MLFLOW_EXPERIMENT_NAME:-fraud-detection}

  prefect-server:
    image: prefecthq/prefect:3-latest
    command: prefect server start --host 0.0.0.0 --port 4200
    ports:
      - "4200:4200"
  prefect-worker:
    build:
      context: .
      dockerfile: ./infra/orchestration/prefect/Dockerfile

    environment:
      PREFECT_API_URL: http://prefect-server:4200/api

    volumes:
      - ./infra/orchestration/prefect:/app
    command: >
      sh -c "
      sleep 20 &&
      prefect worker start --pool docker-pool
      "
    depends_on:
      - prefect-server

volumes:
  minio_data:
