version: '3.8'
services:
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    
  jobmanager:
    build: 
      context: .
      dockerfile: ./infra/compute/flink/Dockerfile
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    volumes:
      - .:/opt/flink/usrlib

  taskmanager:
    build: 
      context: .
      dockerfile: ./infra/compute/flink/Dockerfile
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        taskmanager.memory.process.size: 4096m
        taskmanager.memory.framework.off-heap.size: 256m
        taskmanager.memory.task.off-heap.size: 512m
    volumes:
      - .:/opt/flink/usrlib

  serving-api:
    build:
      context: .
      dockerfile: ./serving/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app

  minio:
    build:
      context: .
      dockerfile: ./infra/storage/minio/Dockerfile
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD; do
        echo 'waiting for minio...';
        sleep 2;
      done;

      mc mb -p local/mlflow;

      echo 'bucket created';
      "
  mlflow:
    build:
      context: .
      dockerfile: ./infra/tracking/mlflow/Dockerfile

    ports:
      - "5000:5000"

    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-minioadmin}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-minioadmin}
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - MLFLOW_SERVER_ALLOWED_HOSTS=*
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root s3://mlflow
      --serve-artifacts 
    depends_on:
      - minio

  training:
    build:
      context: .
      dockerfile: ./training/Dockerfile
    depends_on:
      - mlflow
      - minio
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI:-http://mlflow:5000}
      - MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT_URL:-http://minio:9000}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-minioadmin}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-minioadmin}
      - MLFLOW_EXPERIMENT_NAME=${MLFLOW_EXPERIMENT_NAME:-fraud-detection}
    volumes:
      - .:/app

volumes:
  minio_data: